title: Mileena Rayne
description: Musician, Writer, Truth-Teller
url: https://mileenarayne.com
baseurl: ""

permalink: /diary/:year/:month/:day/:title/

collections:
  posts:
    output: true
    permalink: /diary/:year/:month/:day/:title/
  chapters:
    output: true
    permalink: /chapters/:path/

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

markdown: kramdown
highlighter: rouge
timezone: America/Chicago

# Process all files, even in subdirectories
keep_files:
  - chapters
