title: Mileena Rayne
description: Musician, Writer, Truth-Teller
url: https://mileena28.github.io
baseurl: ""

# Permalink structure for blog posts
permalink: /diary/:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /diary/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Markdown settings
markdown: kramdown
highlighter: rouge

# Site settings
timezone: America/Chicago
