# Site Information
title: Mileena Rayne
tagline: Musician, Writer, Truth-Teller
description: "Dark fantasy author and musician creating raw, honest stories about trauma, faith, and human resilience. Read Blood of the Wild Gods series and listen to original songs about mental health."
url: https://mileenarayne.com
baseurl: ""

# SEO Settings
title_separator: "|"
name: Mileena Rayne
author:
  name: Mileena Rayne
  bio: "Registered Nurse, author of Blood of the Wild Gods series, and musician writing songs about mental health, trauma, and truth."
  location: "Minnesota, USA"

# Social Media (for SEO and sharing)
social:
  name: Mileena Rayne
  links:
    - https://www.facebook.com/share/16qhtJiSk8/?mibextid=wwXIfr
    - https://www.instagram.com/mileenarayne
    - https://www.tiktok.com/@mileena_rayne
    - https://x.com/mileena_rayne
    - https://open.spotify.com/artist/0DZlZexMYSKS7twfxpcM0P
    - https://youtube.com/@mileenarayne
    - https://linktr.ee/mileenarayne

# Content Settings
permalink: /diary/:year/:month/:day/:title/

collections:
  posts:
    output: true
    permalink: /diary/:year/:month/:day/:title/
  chapters:
    output: true
    permalink: /chapters/:path/
  # Add world guide as a collection to ensure proper processing
  world_guide:
    output: true
    permalink: /world-guide/:path/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

# Sitemap Configuration
sitemap:
  path: sitemap.xml
  
# Build Settings
markdown: kramdown
highlighter: rouge
timezone: America/Chicago

# Include files and directories that should be processed
include:
  - world-guide
  - _pages

# Keep these files during build
keep_files:
  - chapters
  - world-guide

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - CNAME
  - Makefile
  - "*.gemspec"
  - "*.gem"
  - .gitignore

# SEO Defaults
defaults:
  # Posts defaults
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Mileena Rayne"
      image: "/assets/images/blood-of-the-wild-gods.png"
      sitemap:
        priority: 0.6
        changefreq: "monthly"
  
  # Chapters defaults - HIGH PRIORITY for book content
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"
      author: "Mileena Rayne"
      image: "/assets/images/EbookPic.jpg"
      sitemap:
        priority: 0.8
        changefreq: "monthly"
  
  # World Guide defaults
  - scope:
      path: "world-guide"
    values:
      layout: "default"
      author: "Mileena Rayne"
      image: "/assets/images/blood-of-the-wild-gods.png"
      sitemap:
        priority: 0.5
        changefreq: "yearly"
  
  # Default image for all pages
  - scope:
      path: ""
    values:
      image: "/assets/images/mileena-rayne-author.jpg"
  
  # Exclude admin/drafts from sitemap
  - scope:
      path: "admin/*"
    values:
      sitemap: false
  - scope:
      path: "_drafts/*"
    values:
      sitemap: false
  - scope:
      path: "404.html"
    values:
      sitemap: false
  - scope:
      path: "403.html"
    values:
      sitemap: false
  - scope:
      path: "offline.html"
    values:
      sitemap: false

# High priority pages (for sitemap)
navigation:
  - url: /
    priority: 1.0
    changefreq: weekly
  - url: /writing/
    priority: 0.9
    changefreq: weekly
  - url: /music/
    priority: 0.8
    changefreq: monthly
  - url: /diary/
    priority: 0.8
    changefreq: weekly
  - url: /about/
    priority: 0.7
    changefreq: monthly
  - url: /community/
    priority: 0.7
    changefreq: weekly
  - url: /world-guide/
    priority: 0.7
    changefreq: monthly
  - url: /contact/
    priority: 0.5
    changefreq: yearly

# Enhanced SEO settings
breadcrumbs: true

# Rich snippets for organization
organization:
  name: "Mileena Rayne"
  url: "https://mileenarayne.com"
  logo: "https://mileenarayne.com/assets/images/mileena-rayne-logo.jpg"
  social_links:
    - "https://www.facebook.com/share/16qhtJiSk8/?mibextid=wwXIfr"
    - "https://www.instagram.com/mileenarayne"
    - "https://open.spotify.com/artist/0DZlZexMYSKS7twfxpcM0P"
    - "https://youtube.com/@mileenarayne"

# Feed settings (for RSS)
feed:
  posts_limit: 20
  path: feed.xml
  
# Compression (if using jekyll-compress-html)
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
